export const RecipeDb = [
    {
      name: "Spaghetti Bolognese",
      imageLink: "https://example.com/spaghetti.jpg",
      cuisine: "Italian",
      ingredients: [
        "250g spaghetti",
        "300g ground beef",
        "1 onion, chopped",
        "2 cloves of garlic, minced",
        "400g canned tomatoes",
        "2 tablespoons tomato paste",
        "1 teaspoon dried oregano",
        "Salt and pepper to taste",
        "Grated Parmesan cheese for serving",
      ],
      instructions: [
        "Cook the spaghetti according to the package instructions.",
        "In a large pan, heat some oil and cook the onion until softened.",
        "Add the ground beef and garlic to the pan, and cook until browned.",
        "Stir in the canned tomatoes, tomato paste, dried oregano, salt, and pepper. Simmer for 15-20 minutes.",
        "Serve the sauce over the cooked spaghetti, topped with grated Parmesan cheese.",
      ],
    },
    {
      name: "Chicken Curry",
      imageLink: "https://example.com/chicken_curry.jpg",
      cuisine: "Indian",
      ingredients: [
        "500g chicken, cut into pieces",
        "1 onion, finely chopped",
        "2 cloves of garlic, minced",
        "1 tablespoon curry powder",
        "1 teaspoon ground turmeric",
        "1 teaspoon ground cumin",
        "1 can coconut milk",
        "Salt and pepper to taste",
        "Fresh cilantro for garnish",
      ],
      instructions: [
        "Heat some oil in a large pan and sauté the onion and garlic until golden.",
        "Add the chicken pieces and cook until browned.",
        "Sprinkle curry powder, turmeric, and cumin over the chicken. Stir well to coat.",
        "Pour in the coconut milk and simmer for 20-25 minutes until the chicken is cooked through.",
        "Season with salt and pepper, and garnish with fresh cilantro before serving.",
      ],
    },
    {
      name: "Caprese Salad",
      imageLink: "https://example.com/caprese_salad.jpg",
      cuisine: "Italian",
      ingredients: [
        "2 ripe tomatoes",
        "250g fresh mozzarella cheese",
        "Handful of fresh basil leaves",
        "2 tablespoons extra virgin olive oil",
        "1 tablespoon balsamic vinegar",
        "Salt and pepper to taste",
      ],
      instructions: [
        "Slice the tomatoes and mozzarella cheese into thick slices.",
        "Arrange the tomato and mozzarella slices on a plate, alternating between them.",
        "Place a basil leaf on top of each tomato and mozzarella slice.",
        "Drizzle the olive oil and balsamic vinegar over the salad.",
        "Season with salt and pepper to taste.",
      ],
    },
  ];
  